apiVersion: batch/v1
kind: CronJob
metadata:
  name: card-list-rearrangement
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: card-list-rearrangement
            image: ghcr.io/hsiaofongw/get-notion-rss-feeds:0.0.8
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - scripts/rearrange-my-notion-cards-db.sh
            env:
            - name: DATA_GITHUB_FRIEND_LINK_LIST_JSON
              valueFrom:
                configMapKeyRef:
                  name: get-notion-rss-feeds-configmap
                  key: data_github_friend_link_list_json
                  optional: false
            - name: NOTION_FRIEND_LINK_LIST_DB_ID
              valueFrom:
                configMapKeyRef:
                  name: get-notion-rss-feeds-configmap
                  key: friend_link_list_db_id
                  optional: false
            - name: NOTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notion-integration-keys
                  key: get-notion-rss-feeds-integration-key
                  optional: false
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-github-link-list-and-sync-into-notion-db
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetch-github-link-list-and-sync-into-notion-db
            image: ghcr.io/hsiaofongw/get-notion-rss-feeds:0.0.8
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - scripts/sync-my-github-friends-to-notion-db.sh
            env:
            - name: DATA_GITHUB_FRIEND_LINK_LIST_JSON
              valueFrom:
                configMapKeyRef:
                  name: get-notion-rss-feeds-configmap
                  key: data_github_friend_link_list_json
                  optional: false
            - name: NOTION_FRIEND_LINK_LIST_DB_ID
              valueFrom:
                configMapKeyRef:
                  name: get-notion-rss-feeds-configmap
                  key: friend_link_list_db_id
                  optional: false
            - name: NOTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notion-integration-keys
                  key: get-notion-rss-feeds-integration-key
                  optional: false
          restartPolicy: Never
