apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-notion-rss-feeds
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - exploro.one
      secretName: exploro-one-tls-secret
    - hosts:
        - beyondstars.xyz
      secretName: beyondstars-xyz-tls-secret
  rules:
    - host: exploro.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: get-notion-rss-feeds
                port:
                  number: 80
    - host: beyondstars.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: get-notion-rss-feeds
                port:
                  number: 80
