apiVersion: v1
kind: Service
metadata:
  name: get-notion-rss-feeds
  labels:
    app: rss
spec:
  ports:
    - name: web
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: get-notion-rss-feeds
